### PR TITLE
Review going.to.sleep.short.dialog it-it

### PR DESCRIPTION
**Pull request by denics**

### CODE REVIEW

**Comment by denics** [comment]
This will be obsoleted once #13 will be merged. I will take care of it then.

**Comment by JarbasAl** [comment]
is this still valid @denics ?

**Comment by denics** [comment]
so #13 has been merged :) It looks like I have some work to do :)

**Comment by JarbasAl** [comment]
please reopen from https://gitlocalize.com/repo/9608

**Pull request closed without merging**
